import './sendOFT'
import './verify/verifyAmoy'
import './verify/verifyBscTestnet'
import './verify/verifySepolia'
import './verify/verifyFuji'
import './verify/verifyRootstock'
import './verify/verifyArb'
import './setPeer'
import './getPeer'
import './debug'
import './debug2'
import './send/sendOFT'
import './setupEnv'
import './verify/verifyStaking'
import './staking/stakingUSDT'
import './staking/approveOFT'

export const MODE = process.env.MODE === 'main'
export const CI_BSC = MODE ? process.env.CI_BSC : 97
